### ISSUE TITLE
Feature: Make the project more contributor friendly

### ISSUE THREAD

**Issue by orama254** [hhhrrrttt222111/PyBox#6]
Greetings @hhhrrrttt222111 

as per Github's recommended community standards, the project seems to be missing some items on the checklist namely

 - [ ] Code of conduct
 - [x] Contributing guidelines #11 
 - [x] License #10 
 
#### screenshot :
![Pybox](https://user-images.githubusercontent.com/50571688/135817909-55af07f4-94bb-4959-b4f8-e86bd59dda80.jpg)

I'd be happy to add them to the project if you need any assistance with this

**Comment by hhhrrrttt222111** [comment]
> Greetings @hhhrrrttt222111
> 
> as per Github's recommended community standards, the project seems to be missing some items on the checklist namely
> 
> * [ ]  Code of conduct
> * [ ]  Contributing guidelines
> * [ ]  License
> 
> #### screenshot :
> ![Pybox](https://user-images.githubusercontent.com/50571688/135817909-55af07f4-94bb-4959-b4f8-e86bd59dda80.jpg)
> 
> I'd be happy to add them to the project if you need any assistance with this

Add MIT License and Contributing.md

**Comment by orama254** [comment]
> > Greetings @hhhrrrttt222111
> > as per Github's recommended community standards, the project seems to be missing some items on the checklist namely
> > 
> > * [ ]   Code of conduct
> > * [ ]   Contributing guidelines
> > * [ ]   License
> > 
> > #### screenshot :
> > ![Pybox](https://user-images.githubusercontent.com/50571688/135817909-55af07f4-94bb-4959-b4f8-e86bd59dda80.jpg)
> > I'd be happy to add them to the project if you need any assistance with this
> 
> Add MIT License and Contributing.md

Cool...working on it
